-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Clientes"
(
    direccion_cli character(50) COLLATE pg_catalog."default" NOT NULL,
    id_cli integer NOT NULL,
    nombre_cli name COLLATE pg_catalog."default" NOT NULL,
    telefono_cli numeric NOT NULL,
    inmueble_preferido_cli character(50) COLLATE pg_catalog."default" NOT NULL,
    importe_maximo_cli money NOT NULL,
    CONSTRAINT "Clientes_pkey" PRIMARY KEY (id_cli)
);

CREATE TABLE IF NOT EXISTS public.factura
(
    id_fac integer NOT NULL,
    importe_fac money NOT NULL,
    metodo_pago character(50) COLLATE pg_catalog."default" NOT NULL,
    importe_deposito money NOT NULL,
    plazo_pago date NOT NULL,
    observaciones character(200) COLLATE pg_catalog."default" NOT NULL,
    id_cli integer NOT NULL,
    CONSTRAINT factura_pkey PRIMARY KEY (id_fac)
);

CREATE TABLE IF NOT EXISTS public.pago
(
    id_pag integer NOT NULL,
    importe money NOT NULL,
    fecha_pag date NOT NULL,
    id_fac integer NOT NULL,
    CONSTRAINT pago_pkey PRIMARY KEY (id_pag)
);

ALTER TABLE IF EXISTS public.factura
    ADD CONSTRAINT id_cli FOREIGN KEY (id_cli)
    REFERENCES public."Clientes" (id_cli) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT id_fac FOREIGN KEY (id_fac)
    REFERENCES public.factura (id_fac) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;